[package]
name = "hevoicechanger"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Ultra-low latency Linux AI Voice Changer (Direct Mic to Speaker)"
repository = "https://github.com/ultrapg/hevoicechanger"

[dependencies]
ort = { version = "2.0.0-rc.9", features = ["webgpu"] }
cpal = "0.15"
rtrb = "0.3"
eframe = "0.27"
ndarray = "0.15"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
hound = "3.5"
ctrlc = { version = "3.4", features = ["termination"] }
pitch_shift = "2.1.0"
tdpsola = "0.1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release.package."*"]
opt-level = 3

